import {
    BanknoteIcon,
    CalendarIcon,
    CircleDotIcon,
    FolderIcon,
    HashIcon,
    HeadingIcon,
    IdCardIcon,
    LanguagesIcon,
    LinkIcon,
    ListOrderedIcon,
    MailIcon,
    PackageIcon,
    PhoneIcon,
    ShieldIcon,
    ShapesIcon,
    TypeIcon,
    UserRoundIcon,
    UsersIcon,
    WifiIcon,
    Image,
    type LucideIcon,
    CalendarClockIcon,
} from 'lucide-react';

export const DEFAULT_COLUMN_ICONS: Record<string, LucideIcon> = {
    name: UserRoundIcon,
    customer: UserRoundIcon,
    title: TypeIcon,
    label: HeadingIcon,
    email: MailIcon,
    phone: PhoneIcon,
    nrc_number: IdCardIcon,
    contact_point: PhoneIcon,
    status: CircleDotIcon,
    is_active: CircleDotIcon,
    created_at: CalendarClockIcon,
    updated_at: CalendarClockIcon,
    date: CalendarIcon,
    start_date: CalendarIcon,
    end_date: CalendarIcon,
    dates: CalendarIcon,
    roles: ShieldIcon,
    permissions_count: ShieldIcon,
    users_count: UsersIcon,
    accounts_count: WifiIcon,
    account_number: WifiIcon,
    package: PackageIcon,
    package_name: PackageIcon,
    type: ShapesIcon,
    serial_no: HashIcon,
    amount: BanknoteIcon,
    lang: LanguagesIcon,
    slug: LinkIcon,
    category_name: FolderIcon,
    sort_order: ListOrderedIcon,
    image: Image,
};
